version: '3.9'

services:
  front:
    build:
      context: Frontend/
    ports:
      - "8080:3000"
    volumes:
      - ./Frontend/app:/app
      - ./Frontend/app/node_modules:/app/node_modules
    command: sh -c "npm run dev"
    networks:
      - default
      - snowboard_default
  # app:
  # db:
volumes:
  node_modules:
networks:
  snowboard_default:
    external: true

