version: '3.9'

services:
  front:
    build:
      context: Frontend/
    container_name: next
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/app:/app
      - ./Frontend/app/node_modules:/app/node_modules
    command: sh -c "npm run dev"
    depends_on:
      - back
      - db
  back:
    container_name: rails
    build: 
      context: ./Backend
    tty: true
    volumes:
      - ./Backend/rails/:/app
    ports:
      - "8080:3000"
    command: bash -c "bundle e rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./Backend/rails/tmp/db:/var/lib/postgresql/data
volumes:
  node_modules:

